Build using `Dockerfile`
...instead of heroku/buildpacks:20, because it is EoL:

    ERROR: This builder image (heroku/buildpacks:20) has been sunset,
    since it uses legacy shimmed classic Heroku buildpacks, rather than
    Heroku's next-generation Cloud Native Buildpacks.

    As such, this image is no longer supported and does not receive any
    security updates or fixes.

(message printed when building with it)

there is this escape hatch, but we need to move on at some point

    To ignore this error, set the env var ALLOW_EOL_SHIMMED_BUILDER to 1.